proxy-groups:
  - name: TikTok
    type: url-test
    filter: ""
    exclude-filter: é¦™æ¸¯|è‹±å›½|å°åº¦
    hidden: true
    icon: ""
    include-all: true
    url: https://www.gstatic.com/generate_204
    interval: 300
    tolerance: 150
    lazy: true
    disable-udp: false

  - name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
    type: select
    filter: ""
    exclude-filter: ""
    hidden: false
    icon: ""
    proxies:
      - ğŸˆ è‡ªåŠ¨é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
    disable-udp: false

  - name: ğŸˆ è‡ªåŠ¨é€‰æ‹©
    type: url-test
    filter: ""
    exclude-filter: ""
    hidden: false
    icon: ""
    include-all: true
    url: https://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    lazy: true
    disable-udp: false

  - name: ğŸ¯ å…¨çƒç›´è¿
    type: select
    filter: ""
    exclude-filter: ""
    hidden: true
    icon: ""
    proxies:
      - DIRECT
      - REJECT
    disable-udp: false

  - name: ğŸ›‘ å…¨çƒæ‹¦æˆª
    type: select
    filter: ""
    exclude-filter: ""
    hidden: true
    icon: ""
    proxies:
      - REJECT
      - DIRECT
    disable-udp: false

  - name: ğŸŸ æ¼ç½‘ä¹‹é±¼
    type: select
    filter: ""
    exclude-filter: ""
    hidden: true
    icon: ""
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
    disable-udp: false

rule-providers:
  Adobe:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/610841887/rule/refs/heads/main/adobe.yaml

  tiktok:
    type: http
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/610841887/rule/refs/heads/main/geosite_tiktok.yaml

  å¸¸ç”¨å·¥å…·åŸŸå:
    type: http
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/610841887/rule/refs/heads/main/cn.yaml

  category-ads-all:
    type: http
    url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/category-ads-all.mrs
    behavior: domain
    format: mrs
    proxy: ğŸ¯ å…¨çƒç›´è¿

  GEOIP-Private:
    type: http
    url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/private.mrs
    behavior: ipcidr
    format: mrs
    proxy: ğŸ¯ å…¨çƒç›´è¿

  GEOIP-CN:
    type: http
    url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/cn.mrs
    behavior: ipcidr
    format: mrs
    proxy: ğŸ¯ å…¨çƒç›´è¿

  GEOSITE-Private:
    type: http
    url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/private.mrs
    behavior: domain
    format: mrs
    proxy: ğŸ¯ å…¨çƒç›´è¿

  GEOSITE-CN:
    type: http
    url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/cn.mrs
    behavior: domain
    format: mrs
    proxy: ğŸ¯ å…¨çƒç›´è¿

  geolocation-!cn:
    type: http
    url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/geolocation-!cn.mrs
    behavior: domain
    format: mrs
    proxy: ğŸ¯ å…¨çƒç›´è¿

rules:
  - RULE-SET,Adobe,ğŸ›‘ å…¨çƒæ‹¦æˆª
  - RULE-SET,tiktok,TikTok,no-resolve
  - RULE-SET,å¸¸ç”¨å·¥å…·åŸŸå,ğŸ¯ å…¨çƒç›´è¿,no-resolve
  - AND,((DST-PORT,443),(NETWORK,udp)),ğŸ›‘ å…¨çƒæ‹¦æˆª
  - RULE-SET,category-ads-all,ğŸ›‘ å…¨çƒæ‹¦æˆª
  - RULE-SET,GEOIP-Private,ğŸ¯ å…¨çƒç›´è¿,no-resolve
  - RULE-SET,GEOIP-CN,ğŸ¯ å…¨çƒç›´è¿,no-resolve
  - RULE-SET,GEOSITE-Private,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,GEOSITE-CN,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,geolocation-!cn,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼

sniffer:
  sniff:
    TLS:
      ports:
        - 443
        - 8443
    HTTP:
      ports:
        - 80
        - 8080
        - 8880
    QUIC:
      ports:
        - 443
        - 8443
  override-destination: false
  enable: true
  force-dns-mapping: true
  skip-domain:
    - Mijia Cloud
    - dlg.io.mi.com
    - +.push.apple.com

dns:
  enable: true
  ipv6: false
  use-hosts: false
  use-system-hosts: true
  nameserver:
    - tls://8.8.8.8#ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  proxy-server-nameserver:
    - https://223.5.5.5/dns-query#ğŸ¯ å…¨çƒç›´è¿
  nameserver-policy:
    rule-set:GEOSITE-CN: https://223.5.5.5/dns-query#ğŸ¯ å…¨çƒç›´è¿
    rule-set:geolocation-!cn: tls://8.8.8.8#ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "*.lan"
    - "*.localdomain"
    - "*.example"
    - "*.invalid"
    - "*.localhost"
    - "*.test"
    - "*.local"
    - "*.home.arpa"
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
  prefer-h3: false

geodata-mode: false
geox-url:
  geoip: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat
  geosite: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat
  mmdb: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb
  asn: https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb
